import type { CountryFieldSpec } from '@/lib/country-intelligence-contract'

/**
 * Lot initial : sentinelle de pack + une section objet par pilier métier.
 * Les objets section peuvent contenir `summary`, `sourced_entries`, etc. (voir morocco-research-pack).
 */
export const COUNTRY_MOROCCO_RESEARCH_CONTRACT: CountryFieldSpec[] = [
  {
    key: 'mr_pack_version_marker',
    path: 'full_data.morocco_research_pack._pack_version',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'string',
    justification: 'Marqueur explicite qu’un pack Maroc est maintenu pour ce pays.',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_immigration_legal',
    path: 'full_data.morocco_research_pack.immigration_legal',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Bloc immigration & légal (visa MAR, durées, statuts, accords…).',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_work_business',
    path: 'full_data.morocco_research_pack.work_business',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Travail, secteurs, street food, difficulté admin, salaires indicatifs…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_education',
    path: 'full_data.morocco_research_pack.education',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Études, bourses, coûts, langues, travail pendant études…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_costs_life_mad',
    path: 'full_data.morocco_research_pack.costs_life_mad',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Coûts MAD, logement, budget vacances, inflation, devise…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_society_demographics',
    path: 'full_data.morocco_research_pack.society_demographics',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Démographie, langues, diaspora MAR, intégration…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_mobility_transport',
    path: 'full_data.morocco_research_pack.mobility_transport',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Vols MAR, escales, visa transit, coûts billets…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_climate_geography',
    path: 'full_data.morocco_research_pack.climate_geography',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Continent, saisons, températures…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_special_programs',
    path: 'full_data.morocco_research_pack.special_programs',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Programmes gouvernementaux, volontariat, accueil…',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_driving_license_detail',
    path: 'full_data.morocco_research_pack.driving_license_detail',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Permis MAR, international, conversion (lens Maroc → destination).',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_qualitative_moroccan_lens',
    path: 'full_data.morocco_research_pack.qualitative_moroccan_lens',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Témoignages, perception, intégration (sources explicites requises).',
    acquisition: 'hybrid',
  },
  {
    key: 'mr_extended_criteria',
    path: 'full_data.morocco_research_pack.extended_criteria',
    domain: 'morocco_decision',
    critical: false,
    expectedType: 'object',
    justification: 'Santé, banque, halal, CPI, etc. — agrégat avant éclatement.',
    acquisition: 'hybrid',
  },
]
